spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_vagas
spring.datasource.username=admin
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

security.token.secret=JAVAGAS_@123#
security.token.secret.candidate=JAVAGAS_@123#CANDIDATE

sonarqube.token=sqp_a92828eb1b06b6e010424cb5b7a6f6791b1ad8c8

management.endpoints.web.exposure.include=*